CREATE TABLE `user`
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	create_time DATETIME DEFAULT NOW(),
	last_update_time DATETIME
);

CREATE TABLE note
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user` BIGINT UNSIGNED NOT NULL,
	title VARCHAR(50) NOT NULL,
	contents TEXT,
	create_time DATETIME DEFAULT NOW(),
	last_update_time DATETIME,
	
	FOREIGN KEY (`user`) REFERENCES `user`(id)
);
